05/04/2020 at 04:41:19 AM - __main__ - <ipython-input-3-4d51e5dc93e9>.<module> in 2 - INFO: Mensagem informativa: Oiiii
05/04/2020 at 04:41:20 AM - __main__ - <ipython-input-4-561e5e6cba1f>.<module> in 1 - DEBUG: Mensagem importante
05/04/2020 at 04:41:21 AM - __main__ - <ipython-input-5-c4cc73e6a179>.<module> in 1 - DEBUG: Mensagem de debug
05/04/2020 at 04:41:22 AM - __main__ - <ipython-input-6-0fa808d47c74>.<module> in 1 - ERROR: Algum erro aconteceu
05/04/2020 at 04:41:23 AM - __main__ - <ipython-input-7-f42fe8a0d5cc>.<module> in 1 - CRITICAL: Algum erro grave aconteceu
05/04/2020 at 04:41:25 AM - __main__ - <ipython-input-8-af982d37c944>.<module> in 4 - ERROR: Exception
Traceback (most recent call last):
  File "<ipython-input-8-af982d37c944>", line 2, in <module>
    open('file.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'file.txt'
